-- ******************************************************
-- identityColumns.sql
--
-- Description:   This script contains sample SQL
--
-- Author:  Maria R. Garcia Altobello
--
-- Date:   October, 2017
--
-- ******************************************************

-- ******************************************************
--    SPOOL SESSION
--      Creates a transcript of the session
--
--   Note:
--      For this to work properly, you must:
--      set echo on OR create a login.sql file
--
--   Syntax:
--      SPOOL <session_name>.lst
-- ******************************************************

spool s10identityColumns.lst


-- ******************************************************
--   Identity Columns
--            Demonstrates the three types of identity columns
--
--   Note:
--            Save each trigger on a separate file on your
--            scripts directory.  It's easier to call a
--            trigger than it is to copy and paste it
-- ******************************************************

/* ALWAYS */

DROP table tbGiftId purge;

CREATE table tbGiftId (
   giftNo               NUMBER GENERATED ALWAYS AS IDENTITY
      constraint        pk_giftId         primary key,   
   patronID   char(3)         null
      constraint        fk_patronid_tbPatron_Id
         references tbPatron(patronID) on delete set null,   
   gift_date    date            not null, 
   amount       number(11,2)    not null
); 

SELECT * from tbGiftId;

INSERT into tbGiftId
   (patronID, gift_date, amount)
   values
   (111, sysdate, 500);

SELECT * from tbGiftId;

INSERT into tbGiftId
   values (32, 111, sysdate, 500);

INSERT into tbGiftId
   values (NULL, 111, sysdate, 500);

/* BY DEFAULT */

DROP table tbGiftId purge;

CREATE table tbGiftId (
   giftNo               NUMBER GENERATED BY DEFAULT AS IDENTITY
      constraint        pk_giftId         primary key,   
   patronID   char(3)         null
      constraint        fk_patronid_tbPatron_Id
         references tbPatron(patronID) on delete set null,   
   gift_date    date            not null, 
   amount       number(11,2)    not null
); 

SELECT * from tbGiftId;

INSERT into tbGiftId
   (patronID, gift_date, amount)
   values
   (111, sysdate, 500);

SELECT * from tbGiftId;

INSERT into tbGiftId
   values (32, 111, sysdate, 500);

SELECT * from tbGiftId;

INSERT into tbGiftId
   values (NULL, 111, sysdate, 500);

/* BY DEFAULT ON NULL */

DROP table tbGiftId purge;

CREATE table tbGiftId (
   giftNo               NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY
      constraint        pk_giftId         primary key,   
   patronID   char(3)         null
      constraint        fk_patronid_tbPatron_Id
         references tbPatron(patronID) on delete set null,   
   gift_date    date            not null, 
   amount       number(11,2)    not null
); 

SELECT * from tbGiftId;

INSERT into tbGiftId
   (patronID, gift_date, amount)
   values
   (111, sysdate, 500);

SELECT * from tbGiftId;

INSERT into tbGiftId
   values (32, 111, sysdate, 500);

SELECT * from tbGiftId;

INSERT into tbGiftId
   values (NULL, 111, sysdate, 500);

SELECT * from tbGiftId;


-- ******************************************************
--    END SESSION
--      Closes the transcript file
--
--   Note:
--      If you forget to do it,
--       ORACLE will close it when you log out
--
--   Syntax:
--      SPOOL off
-- ******************************************************

spool off
